export default {
    topNav:[
        {tit:"平台首页",url:"/static/images/index-top.png"},
        {tit:"个人工作台",url:"/static/images/grkj-top.png"},
        {tit:"资源中心",url:"/static/images/zy-top.png"},
        {tit:"智慧教与学",url:"/static/images/study-top.png"},
        {tit:"教研中心",url:"/static/images/jy-top.png"},
        {tit:"活动大赛",url:"/static/images/activity-top.png"}
    ],
    bannerData:[
        {tit:"平台首页",url:"http://castic.xiaoxiaotong.org/images/banners/b1.jpg"},
        {tit:"个人工作台",url:"http://castic.xiaoxiaotong.org/images/banners/b2.jpg"},
        {tit:"资源中心",url:"http://castic.xiaoxiaotong.org/images/banners/b3.jpg"},
        {tit:"智慧教与学",url:"http://castic.xiaoxiaotong.org/images/banners/b4.jpg"},
        {tit:"教研中心",url:"http://castic.xiaoxiaotong.org/images/banners/b5.jpg"}
    ],
    bannerData1:[
        {tit:"平台首页",url:"http://castic.xiaoxiaotong.org/images/banners/b1.jpg"},
        {tit:"个人工作台",url:"http://castic.xiaoxiaotong.org/images/banners/b2.jpg"},
        {tit:"资源中心",url:"http://castic.xiaoxiaotong.org/images/banners/b3.jpg"},
        {tit:"智慧教与学",url:"http://castic.xiaoxiaotong.org/images/banners/b4.jpg"},
        {tit:"教研中心",url:"http://castic.xiaoxiaotong.org/images/banners/b5.jpg"}
    ],
    newData:[
        {"time":"02/02","year":"2018","tit":"虚拟仿真实验室上线公告","content":"各位老师、同学们：大家好。为了更好的为大家服务，同为了丰富青岛教育资源库，虚拟仿真实验室在大家的努力式上线了。虚拟仿真实验室覆盖了初高中物理、化学等......"},
        {"time":"02/02","year":"2018","tit":"虚拟仿真实验室上线公告","content":"各位老师、同学们：大家好。为了更好的为大家服务，同为了丰富青岛教育资源库，虚拟仿真实验室在大家的努力式上线了。虚拟仿真实验室覆盖了初高中物理、化学等......"},
        {"time":"02/02","year":"2018","tit":"虚拟仿真实验室上线公告","content":"各位老师、同学们：大家好。为了更好的为大家服务，同为了丰富青岛教育资源库，虚拟仿真实验室在大家的努力式上线了。虚拟仿真实验室覆盖了初高中物理、化学等......"},
        {"time":"02/02","year":"2018","tit":"虚拟仿真实验室上线公告","content":"各位老师、同学们：大家好。为了更好的为大家服务，同为了丰富青岛教育资源库，虚拟仿真实验室在大家的努力式上线了。虚拟仿真实验室覆盖了初高中物理、化学等......"},
    ],
    newActivity:[
        {
            "time":"2018-03-05 00:00—2018-03-31 23:55",
            "intro":"适用对象：青岛市中小学学生活动目的：给学生提供展示朗诵才能的平台，激发学生对朗诵艺术的兴趣，掌握朗诵技巧，提高朗诵能力。",
            "tit":"虚拟仿真实验室上线公告",
            "zhinan":"活动指南",
            "zhanshi":"作品展示",
            "fabu":"作品发布",
            "url":"/static/images/activity.png",
            "status":1
        },
        {
            "time":"2018-03-05 00:00—2018-03-31 23:55",
            "intro":"适用对象：青岛市中小学学生活动目的：给学生提供展示朗诵才能的平台，激发学生对朗诵艺术的兴趣，掌握朗诵技巧，提高朗诵能力。",
            "tit":"虚拟仿真实验室上线公告",
            "zhinan":"活动指南",
            "zhanshi":"作品展示",
            "fabu":"作品发布",
            "url":"/static/images/activity.png",
            "status":0
        },     
    ],
    oldActivity:[
        {
            "thumb":"/static/images/old-thumb.png",
            "tit":"虚拟仿真实验室上线公告",
            "time":"2018-03-05 00:00—2018-03-31 23:55",
            "zuopin":"222",
            "peoNum":"21",
            "productions":[
                {
                    "url":"/static/images/activity.png",
                    "name":"《我的青春我做主》",
                    "people":"花花",
                    "subject":"语文",
                    "school":"青岛市黄岛区王台初级中学"
                },
                {
                    "url":"/static/images/activity.png",
                    "name":"《我的青春我做主》",
                    "people":"花花",
                    "subject":"语文",
                    "school":"青岛市黄岛区王台初级中学"
                },
                {
                    "url":"/static/images/activity.png",
                    "name":"《我的青春我做主》",
                    "people":"花花",
                    "subject":"语文",
                    "school":"青岛市黄岛区王台初级中学"
                },
                {
                    "url":"/static/images/activity.png",
                    "name":"《我的青春我做主》",
                    "people":"花花",
                    "subject":"语文",
                    "school":"青岛市黄岛区王台初级中学"
                },
                {
                    "url":"/static/images/activity.png",
                    "name":"《我的青春我做主》",
                    "people":"花花",
                    "subject":"语文",
                    "school":"青岛市黄岛区王台初级中学"
                },
                {
                    "url":"/static/images/activity.png",
                    "name":"《我的青春我做主》",
                    "people":"花花",
                    "subject":"语文",
                    "school":"青岛市黄岛区王台初级中学"
                }
            ]
        },
        {
            "thumb":"/static/images/old-thumb.png",
            "tit":"虚拟仿真实验室上线公告",
            "time":"2018-03-05 00:00—2018-03-31 23:55",
            "zuopin":"222",
            "peoNum":"21",
            "productions":[
                {
                    "url":"/static/images/activity.png",
                    "name":"《我的青春我做主》",
                    "people":"花花",
                    "subject":"语文",
                    "school":"青岛市黄岛区王台初级中学"
                },
                {
                    "url":"/static/images/activity.png",
                    "name":"《我的青春我做主》",
                    "people":"花花",
                    "subject":"语文",
                    "school":"青岛市黄岛区王台初级中学"
                },
                {
                    "url":"/static/images/activity.png",
                    "name":"《我的青春我做主》",
                    "people":"花花",
                    "subject":"语文",
                    "school":"青岛市黄岛区王台初级中学"
                },
                {
                    "url":"/static/images/activity.png",
                    "name":"《我的青春我做主》",
                    "people":"花花",
                    "subject":"语文",
                    "school":"青岛市黄岛区王台初级中学"
                },
                {
                    "url":"/static/images/activity.png",
                    "name":"《我的青春我做主》",
                    "people":"花花",
                    "subject":"语文",
                    "school":"青岛市黄岛区王台初级中学"
                },
                {
                    "url":"/static/images/activity.png",
                    "name":"《我的青春我做主》",
                    "people":"花花",
                    "subject":"语文",
                    "school":"青岛市黄岛区王台初级中学"
                }
            ]
        }
    ],
    Activitying:[
        {
            "time":"2018-03-05 00:00—2018-03-31 23:55",
            "intro":"适用对象：青岛市中小学学生活动目的：给学生提供展示朗诵才能的平台，激发学生对朗诵艺术的兴趣，掌握朗诵技巧，提高朗诵能力。",
            "tit":"虚拟仿真实验室上线公告",
            "zhinan":"活动指南",
            "zhanshi":"作品展示",
            "fabu":"作品发布",
            "url":"/static/images/activity.png",
            "status":1
        },
        {
            "time":"2018-03-05 00:00—2018-03-31 23:55",
            "intro":"适用对象：青岛市中小学学生活动目的：给学生提供展示朗诵才能的平台，激发学生对朗诵艺术的兴趣，掌握朗诵技巧，提高朗诵能力。",
            "tit":"虚拟仿真实验室上线公告",
            "zhinan":"活动指南",
            "zhanshi":"作品展示",
            "fabu":"作品发布",
            "url":"/static/images/activity.png",
            "status":1
        },
        {
            "time":"2018-03-05 00:00—2018-03-31 23:55",
            "intro":"适用对象：青岛市中小学学生活动目的：给学生提供展示朗诵才能的平台，激发学生对朗诵艺术的兴趣，掌握朗诵技巧，提高朗诵能力。",
            "tit":"虚拟仿真实验室上线公告",
            "zhinan":"活动指南",
            "zhanshi":"作品展示",
            "fabu":"作品发布",
            "url":"/static/images/activity.png",
            "status":1
        },
        {
            "time":"2018-03-05 00:00—2018-03-31 23:55",
            "intro":"适用对象：青岛市中小学学生活动目的：给学生提供展示朗诵才能的平台，激发学生对朗诵艺术的兴趣，掌握朗诵技巧，提高朗诵能力。",
            "tit":"虚拟仿真实验室上线公告",
            "zhinan":"活动指南",
            "zhanshi":"作品展示",
            "fabu":"作品发布",
            "url":"/static/images/activity.png",
            "status":1
        },    
        {
            "time":"2018-03-05 00:00—2018-03-31 23:55",
            "intro":"适用对象：青岛市中小学学生活动目的：给学生提供展示朗诵才能的平台，激发学生对朗诵艺术的兴趣，掌握朗诵技巧，提高朗诵能力。",
            "tit":"虚拟仿真实验室上线公告",
            "zhinan":"活动指南",
            "zhanshi":"作品展示",
            "fabu":"作品发布",
            "url":"/static/images/activity.png",
            "status":1
        },
        {
            "time":"2018-03-05 00:00—2018-03-31 23:55",
            "intro":"适用对象：青岛市中小学学生活动目的：给学生提供展示朗诵才能的平台，激发学生对朗诵艺术的兴趣，掌握朗诵技巧，提高朗诵能力。",
            "tit":"虚拟仿真实验室上线公告",
            "zhinan":"活动指南",
            "zhanshi":"作品展示",
            "fabu":"作品发布",
            "url":"/static/images/activity.png",
            "status":1
        },    
        {
            "time":"2018-03-05 00:00—2018-03-31 23:55",
            "intro":"适用对象：青岛市中小学学生活动目的：给学生提供展示朗诵才能的平台，激发学生对朗诵艺术的兴趣，掌握朗诵技巧，提高朗诵能力。",
            "tit":"虚拟仿真实验室上线公告",
            "zhinan":"活动指南",
            "zhanshi":"作品展示",
            "fabu":"作品发布",
            "url":"/static/images/activity.png",
            "status":1
        },
        {
            "time":"2018-03-05 00:00—2018-03-31 23:55",
            "intro":"适用对象：青岛市中小学学生活动目的：给学生提供展示朗诵才能的平台，激发学生对朗诵艺术的兴趣，掌握朗诵技巧，提高朗诵能力。",
            "tit":"虚拟仿真实验室上线公告",
            "zhinan":"活动指南",
            "zhanshi":"作品展示",
            "fabu":"作品发布",
            "url":"/static/images/activity.png",
            "status":1
        },    
        {
            "time":"2018-03-05 00:00—2018-03-31 23:55",
            "intro":"适用对象：青岛市中小学学生活动目的：给学生提供展示朗诵才能的平台，激发学生对朗诵艺术的兴趣，掌握朗诵技巧，提高朗诵能力。",
            "tit":"虚拟仿真实验室上线公告",
            "zhinan":"活动指南",
            "zhanshi":"作品展示",
            "fabu":"作品发布",
            "url":"/static/images/activity.png",
            "status":1
        },
        {
            "time":"2018-03-05 00:00—2018-03-31 23:55",
            "intro":"适用对象：青岛市中小学学生活动目的：给学生提供展示朗诵才能的平台，激发学生对朗诵艺术的兴趣，掌握朗诵技巧，提高朗诵能力。",
            "tit":"虚拟仿真实验室上线公告",
            "zhinan":"活动指南",
            "zhanshi":"作品展示",
            "fabu":"作品发布",
            "url":"/static/images/activity.png",
            "status":1
        },         
    ],
    PreviousAct:[
            {
                "title":"2018",
                " PreviousData":[{
                "thumb":"/static/images/old-thumb.png",
                "tit":"虚拟仿真实验室上线公告",
                "time":"2018-03-05 00:00—2018-03-31 23:55",
                "zuopin":"222",
                "peoNum":"21",
                "productions":[
                    {
                        "url":"/static/images/activity.png",
                        "name":"《我的青春我做主》",
                        "people":"花花",
                        "subject":"语文",
                        "school":"青岛市黄岛区王台初级中学"
                    },
                    {
                        "url":"/static/images/activity.png",
                        "name":"《我的青春我做主》",
                        "people":"花花",
                        "subject":"语文",
                        "school":"青岛市黄岛区王台初级中学"
                    },
                    {
                        "url":"/static/images/activity.png",
                        "name":"《我的青春我做主》",
                        "people":"花花",
                        "subject":"语文",
                        "school":"青岛市黄岛区王台初级中学"
                    },
                    {
                        "url":"/static/images/activity.png",
                        "name":"《我的青春我做主》",
                        "people":"花花",
                        "subject":"语文",
                        "school":"青岛市黄岛区王台初级中学"
                    },
                    {
                        "url":"/static/images/activity.png",
                        "name":"《我的青春我做主》",
                        "people":"花花",
                        "subject":"语文",
                        "school":"青岛市黄岛区王台初级中学"
                    },
                    {
                        "url":"/static/images/activity.png",
                        "name":"《我的青春我做主》",
                        "people":"花花",
                        "subject":"语文",
                        "school":"青岛市黄岛区王台初级中学"
                    }
                ]
            },
            {
                "thumb":"/static/images/old-thumb.png",
                "tit":"虚拟仿真实验室上线公告",
                "time":"2018-03-05 00:00—2018-03-31 23:55",
                "zuopin":"222",
                "peoNum":"21",
                "productions":[
                    {
                        "url":"/static/images/activity.png",
                        "name":"《我的青春我做主》",
                        "people":"花花",
                        "subject":"语文",
                        "school":"青岛市黄岛区王台初级中学"
                    },
                    {
                        "url":"/static/images/activity.png",
                        "name":"《我的青春我做主》",
                        "people":"花花",
                        "subject":"语文",
                        "school":"青岛市黄岛区王台初级中学"
                    },
                    {
                        "url":"/static/images/activity.png",
                        "name":"《我的青春我做主》",
                        "people":"花花",
                        "subject":"语文",
                        "school":"青岛市黄岛区王台初级中学"
                    },
                    {
                        "url":"/static/images/activity.png",
                        "name":"《我的青春我做主》",
                        "people":"花花",
                        "subject":"语文",
                        "school":"青岛市黄岛区王台初级中学"
                    },
                    {
                        "url":"/static/images/activity.png",
                        "name":"《我的青春我做主》",
                        "people":"花花",
                        "subject":"语文",
                        "school":"青岛市黄岛区王台初级中学"
                    },
                    {
                        "url":"/static/images/activity.png",
                        "name":"《我的青春我做主》",
                        "people":"花花",
                        "subject":"语文",
                        "school":"青岛市黄岛区王台初级中学"
                    }
                ]
            }]
        },
        {
            "title":"2017",
            " 2018data":[{
            "thumb":"/static/images/old-thumb.png",
            "tit":"虚拟仿真实验室上线公告",
            "time":"2018-03-05 00:00—2018-03-31 23:55",
            "zuopin":"222",
            "peoNum":"21",
            "productions":[
                {
                    "url":"/static/images/activity.png",
                    "name":"《我的青春我做主》",
                    "people":"花花",
                    "subject":"语文",
                    "school":"青岛市黄岛区王台初级中学"
                },
                {
                    "url":"/static/images/activity.png",
                    "name":"《我的青春我做主》",
                    "people":"花花",
                    "subject":"语文",
                    "school":"青岛市黄岛区王台初级中学"
                },
                {
                    "url":"/static/images/activity.png",
                    "name":"《我的青春我做主》",
                    "people":"花花",
                    "subject":"语文",
                    "school":"青岛市黄岛区王台初级中学"
                },
                {
                    "url":"/static/images/activity.png",
                    "name":"《我的青春我做主》",
                    "people":"花花",
                    "subject":"语文",
                    "school":"青岛市黄岛区王台初级中学"
                },
                {
                    "url":"/static/images/activity.png",
                    "name":"《我的青春我做主》",
                    "people":"花花",
                    "subject":"语文",
                    "school":"青岛市黄岛区王台初级中学"
                },
                {
                    "url":"/static/images/activity.png",
                    "name":"《我的青春我做主》",
                    "people":"花花",
                    "subject":"语文",
                    "school":"青岛市黄岛区王台初级中学"
                }
            ]
        },
        {
            "thumb":"/static/images/old-thumb.png",
            "tit":"虚拟仿真实验室上线公告",
            "time":"2018-03-05 00:00—2018-03-31 23:55",
            "zuopin":"222",
            "peoNum":"21",
            "productions":[
                {
                    "url":"/static/images/activity.png",
                    "name":"《我的青春我做主》",
                    "people":"花花",
                    "subject":"语文",
                    "school":"青岛市黄岛区王台初级中学"
                },
                {
                    "url":"/static/images/activity.png",
                    "name":"《我的青春我做主》",
                    "people":"花花",
                    "subject":"语文",
                    "school":"青岛市黄岛区王台初级中学"
                },
                {
                    "url":"/static/images/activity.png",
                    "name":"《我的青春我做主》",
                    "people":"花花",
                    "subject":"语文",
                    "school":"青岛市黄岛区王台初级中学"
                },
                {
                    "url":"/static/images/activity.png",
                    "name":"《我的青春我做主》",
                    "people":"花花",
                    "subject":"语文",
                    "school":"青岛市黄岛区王台初级中学"
                },
                {
                    "url":"/static/images/activity.png",
                    "name":"《我的青春我做主》",
                    "people":"花花",
                    "subject":"语文",
                    "school":"青岛市黄岛区王台初级中学"
                },
                {
                    "url":"/static/images/activity.png",
                    "name":"《我的青春我做主》",
                    "people":"花花",
                    "subject":"语文",
                    "school":"青岛市黄岛区王台初级中学"
                }
            ]
        }]
    },
    {
        "title":"2018",
        " 2018data":[{
        "thumb":"/static/images/old-thumb.png",
        "tit":"虚拟仿真实验室上线公告",
        "time":"2018-03-05 00:00—2018-03-31 23:55",
        "zuopin":"222",
        "peoNum":"21",
        "productions":[
            {
                "url":"/static/images/activity.png",
                "name":"《我的青春我做主》",
                "people":"花花",
                "subject":"语文",
                "school":"青岛市黄岛区王台初级中学"
            },
            {
                "url":"/static/images/activity.png",
                "name":"《我的青春我做主》",
                "people":"花花",
                "subject":"语文",
                "school":"青岛市黄岛区王台初级中学"
            },
            {
                "url":"/static/images/activity.png",
                "name":"《我的青春我做主》",
                "people":"花花",
                "subject":"语文",
                "school":"青岛市黄岛区王台初级中学"
            },
            {
                "url":"/static/images/activity.png",
                "name":"《我的青春我做主》",
                "people":"花花",
                "subject":"语文",
                "school":"青岛市黄岛区王台初级中学"
            },
            {
                "url":"/static/images/activity.png",
                "name":"《我的青春我做主》",
                "people":"花花",
                "subject":"语文",
                "school":"青岛市黄岛区王台初级中学"
            },
            {
                "url":"/static/images/activity.png",
                "name":"《我的青春我做主》",
                "people":"花花",
                "subject":"语文",
                "school":"青岛市黄岛区王台初级中学"
            }
        ]
    },
    {
        "thumb":"/static/images/old-thumb.png",
        "tit":"虚拟仿真实验室上线公告",
        "time":"2018-03-05 00:00—2018-03-31 23:55",
        "zuopin":"222",
        "peoNum":"21",
        "productions":[
            {
                "url":"/static/images/activity.png",
                "name":"《我的青春我做主》",
                "people":"花花",
                "subject":"语文",
                "school":"青岛市黄岛区王台初级中学"
            },
            {
                "url":"/static/images/activity.png",
                "name":"《我的青春我做主》",
                "people":"花花",
                "subject":"语文",
                "school":"青岛市黄岛区王台初级中学"
            },
            {
                "url":"/static/images/activity.png",
                "name":"《我的青春我做主》",
                "people":"花花",
                "subject":"语文",
                "school":"青岛市黄岛区王台初级中学"
            },
            {
                "url":"/static/images/activity.png",
                "name":"《我的青春我做主》",
                "people":"花花",
                "subject":"语文",
                "school":"青岛市黄岛区王台初级中学"
            },
            {
                "url":"/static/images/activity.png",
                "name":"《我的青春我做主》",
                "people":"花花",
                "subject":"语文",
                "school":"青岛市黄岛区王台初级中学"
            },
            {
                "url":"/static/images/activity.png",
                "name":"《我的青春我做主》",
                "people":"花花",
                "subject":"语文",
                "school":"青岛市黄岛区王台初级中学"
            }
        ]
    }]
},
{
    "title":"2018",
    " 2018data":[{
    "thumb":"/static/images/old-thumb.png",
    "tit":"虚拟仿真实验室上线公告",
    "time":"2018-03-05 00:00—2018-03-31 23:55",
    "zuopin":"222",
    "peoNum":"21",
    "productions":[
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        }
    ]
},
{
    "thumb":"/static/images/old-thumb.png",
    "tit":"虚拟仿真实验室上线公告",
    "time":"2018-03-05 00:00—2018-03-31 23:55",
    "zuopin":"222",
    "peoNum":"21",
    "productions":[
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        }
    ]
}]
},
{
    "title":"2018",
    " 2018data":[{
    "thumb":"/static/images/old-thumb.png",
    "tit":"虚拟仿真实验室上线公告",
    "time":"2018-03-05 00:00—2018-03-31 23:55",
    "zuopin":"222",
    "peoNum":"21",
    "productions":[
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        }
    ]
},
{
    "thumb":"/static/images/old-thumb.png",
    "tit":"虚拟仿真实验室上线公告",
    "time":"2018-03-05 00:00—2018-03-31 23:55",
    "zuopin":"222",
    "peoNum":"21",
    "productions":[
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        }
    ]
}]
},
{
    "title":"2018",
    " 2018data":[{
    "thumb":"/static/images/old-thumb.png",
    "tit":"虚拟仿真实验室上线公告",
    "time":"2018-03-05 00:00—2018-03-31 23:55",
    "zuopin":"222",
    "peoNum":"21",
    "productions":[
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        }
    ]
},
{
    "thumb":"/static/images/old-thumb.png",
    "tit":"虚拟仿真实验室上线公告",
    "time":"2018-03-05 00:00—2018-03-31 23:55",
    "zuopin":"222",
    "peoNum":"21",
    "productions":[
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        }
    ]
}]
},
{
    "title":"2018",
    " 2018data":[{
    "thumb":"/static/images/old-thumb.png",
    "tit":"虚拟仿真实验室上线公告",
    "time":"2018-03-05 00:00—2018-03-31 23:55",
    "zuopin":"222",
    "peoNum":"21",
    "productions":[
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        }
    ]
},
{
    "thumb":"/static/images/old-thumb.png",
    "tit":"虚拟仿真实验室上线公告",
    "time":"2018-03-05 00:00—2018-03-31 23:55",
    "zuopin":"222",
    "peoNum":"21",
    "productions":[
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        },
        {
            "url":"/static/images/activity.png",
            "name":"《我的青春我做主》",
            "people":"花花",
            "subject":"语文",
            "school":"青岛市黄岛区王台初级中学"
        }
    ]
}]
},
    ],  
}